#spring.devtools.livereload.enabled=true

#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.check-template-location=true
#spring.thymeleaf.cache=false

server:
  port: 8000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/finance_data?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: 2142   

  jpa:
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    properties:
      hibernate:
        format_sql: true         

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace 
      SQL: DEBUG      
      
application:
  security:
    jwt:
      secret-key: 6D5A7134743777217A25432A462D4A404E635266556A586E3272357538782F41
      access-token:  
        expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days